stages:
    - vendor
    - test

variables:
    GO111MODULE: "on"

vendor:
    stage: vendor
    image: golang:1.13
    script:
        - go mod vendor
    artifacts:
        paths:
            - vendor
        expire_in: 1 hour

.test: &test_template
    stage: test
    script:
        - go mod download
        - ./script/test_version.sh
        - go test -race -tags=livetest ./...

.nomod: &nomod_template
    stage: test
    script:
        - mkdir -p /go/src
        - ln -s /builds /go/src/github.com
        - cd ${SRCDIR}
        - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
        - dep ensure && dep status
        - ./script/test_version.sh
        - go test -race -tags=livetest ./...

lint:
    stage: test
    image: golang:1.13
    services: []
    before_script:
        - ''
    script:
        - go mod download
        - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $(go env GOPATH)/bin v1.22.2
        - golangci-lint run ./...

go-1.11:
    <<: *test_template
    image: golang:1.11

go-1.12:
    <<: *test_template
    image: golang:1.12

go-1.13:
    <<: *test_template
    image: golang:1.13

go-rc:
    <<: *test_template
    image: golang:rc
    allow_failure: true
