dist: trusty
language: go
go:
    - 1.7.x
    - 1.8.x
    - 1.9.x
    - 1.10.x
    - 1.11.x
    - master
matrix:
    fast_finish: true
    allow_failures:
        - go: master

addons:
  apt:
    sources:
      - sourceline: 'ppa:masterminds/glide'
    packages:
      - glide

install:
    - glide install
    - go get -u gopkg.in/alecthomas/gometalinter.v1 && gometalinter.v1 --install

script:
    - gometalinter.v1 --config .linter.json ./...
